### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by bzbetty** [JornWildt/Macaroons.Net#5]
If this is production ready would you mind submitting a NuGet package?

**Comment by JornWildt** [comment]
Good idea. Will do at some time

**Comment by k15tfu** [comment]
@JornWildt Is there anything we can help you with to get it published on nuget.org?

**Comment by JornWildt** [comment]
Sorry, was busy with other stuff. Its been years since I build this last time, so it will be interesting to see if it works.

Please try https://www.nuget.org/packages/Macaroons.Net/1.0.0 and let me know.

**Comment by JornWildt** [comment]
I tried to upgrade to Libsodium .10 (instead of .6) but then some of the tests started to fail signatures. I'm not going to try to fix that.

**Comment by k15tfu** [comment]
@JornWildt We are unable to use 4.7.2 in our project (actually we work with 4.6.1). Is it possible to make a package for an older .NET Framework version (or make it a multi target project)? The yesterdays version worked fine, btw =)

**Comment by JornWildt** [comment]
Please try again. Now targeting .NET 4.6.

**Comment by k15tfu** [comment]
@JornWildt Yes, now I can reference it in the project and nuget restores it. But I found another issue
```
0>/home/user/Macaroons.Net/packages/Baseclass.Contrib.Nuget.Output.2.1.0/build/net40/Baseclass.Contrib.Nuget.Output.targets(73,5): Error MSB4175 : The task factory "CodeTaskFactory" could not be loaded from the assembly "/usr/lib/mono/msbuild/Current/bin/Microsoft.Build.Tasks.vCurrent.dll". Invalid Image
0>------- Finished building project: Macaroons.Net. Succeeded: False. Errors: 1. Warnings: 0
```

As I can see, upgrading Baseclass.Contrib.Nuget.Output to v2.4.3 solves this problem when running Mono 6.8. This is pretty useful library and I don't know alternative Macaroons impls on C#, especially for Linux. Thank you!

**Comment by JornWildt** [comment]
Lets try again: https://www.nuget.org/packages/Macaroons.Net/1.0.2

**Comment by JornWildt** [comment]
Can I close this issue?

**Comment by k15tfu** [comment]
@JornWildt Hi! Thanks for rebuilding it. Looks like now I faced with https://github.com/baseclass/Contrib.Nuget/issues/57. Want to check if I can do anything with this.

Btw, I fixed tests on Linux: https://github.com/JornWildt/Macaroons.Net/pull/6.

**Comment by k15tfu** [comment]
@JornWildt Is there a reason why Baseclass.Contrib.Nuget.Output is not a development dependency? Looks like setting developmentDependency=true will exclude this dependency from .nupkg and probably everything will be okay.

And can you sign it to generate a PublicKeyToken?

**Comment by JornWildt** [comment]
> And can you sign it to generate a PublicKeyToken?

Do you mean code signing or strong naming or NuGet signing? I cannot do code signing since the "Libsodium-net" package itself is unsigned.

Besides that, try again. V1.03 is with your pull requests.
